// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/nejtr0n/repository-api/src/adapters/git"
	"github.com/nejtr0n/repository-api/src/adapters/gitlab"
	"github.com/nejtr0n/repository-api/src/app"
	"github.com/nejtr0n/repository-api/src/app/command"
	"github.com/nejtr0n/repository-api/src/domain"
	"github.com/nejtr0n/repository-api/src/ports"
	"github.com/urfave/cli/v2"
)

// Injectors from wire.go:

func InitRouter(config *cli.Context) (*gin.Engine, error) {
	gitlabApiToken := domain.NewGitlabApiToken(config)
	gitlabBaseUrl := domain.NewGitlabBaseUrl(config)
	vcs := git.NewVcs(gitlabApiToken)
	provider, err := gitlab.NewProvider(gitlabApiToken, gitlabBaseUrl, vcs)
	if err != nil {
		return nil, err
	}
	providerFactory := domain.NewProviderFactory(provider)
	service := domain.NewService(providerFactory)
	createProjectFromDullHandler := command.NewCreateProjectFromDullHandler(service)
	application := app.NewApplication(createProjectFromDullHandler)
	httpServer := ports.NewHttpServer(application)
	engine := ports.NewRouter(httpServer)
	return engine, nil
}
